services:
  - type: web
    name: capture-application
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/CaptureApplication-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 8